### ISSUE TITLE
Numeric parameter 5 digits long not handled properly

### ISSUE THREAD

**Issue by ThePrez** [IBM/ibmi-db2util#16]
When I use a numeric value >=10000, it is not processed properly. This was discovered when using the QSYS2.NETSTAT_JOB_INFO service. 

The following query works:
`db2util -p 9999 'SELECT JOB_NAME,SLIC_TASK_NAME,LOCAL_PORT from QSYS2.NETSTAT_JOB_INFO WHERE LOCAL_PORT > ? ORDER BY LOCAL_PORT DESC'`

Whereas this one fails:
`db2util -p 10000 'SELECT JOB_NAME,SLIC_TASK_NAME,LOCAL_PORT from QSYS2.NETSTAT_JOB_INFO WHERE LOCAL_PORT > ? ORDER BY LOCAL_PORT DESC'`

Seems some kind of data overflow/underflow issue.

**Comment by ThePrez** [comment]
On cursory inspection, it looks like the value is getting translated at four bytes. For instance:
` db2util -p 99999 'SELECT JOB_NAME,SLIC_TASK_NAME,LOCAL_PORT from QSYS2.NETSTAT_JOB_INFO WHERE LOCAL_PORT > ? ORDER BY LOCAL_PORT DESC'`
seems to process the query as if the parameter was `9999`

I'm guessing `SQLDescribeCol` is returning 4, meaning 4 bytes, when we really want character size. That's just a guess, however.

**Comment by kadler** [comment]
`SQLDescribeCol` wouldn't affect this, since it's the parameter that's the problem. We bind all parameters as SQL_CHAR, but maybe it's having issues with the precision/scale values we're passing back? Or maybe like most things, CLI is just completely garbage when it comes to type conversions.

**Comment by kadler** [comment]
Yes, looks like SQLDescribeParam is giving back 4 for the precision and we pass that back to SQLBindParam. (I believe this is still what the original code from Tony did). Of course, the docs say that shouldn't matter in this case:

> Precision of the corresponding parameter marker.
> * If ParameterType denotes a binary or single-byte character string (for example, SQL_CHAR), this is the maximum length in bytes for this parameter marker.
> * If ParameterType denotes a double-byte character string (for example, SQL_GRAPHIC), this is the maximum length in double-byte characters for this parameter.
> * If ParameterType denotes SQL_DECIMAL or SQL_NUMERIC, this is the maximum decimal precision.
> * Otherwise, this argument is ignored.

In this case the ParameterType (the SQL type retrieved from SQLDescribeParam) is SQL_INTEGER, so according to the above docs this value should be completely ignored. Of course, according to the code, that's not what happens. Since 5.4, the code delegates conversions to SQ Runtime code and it uses this value to tell Runtime how much data there is.

Since we're always going to bind as SQL_C_CHAR, I think we can actually get rid of the whole SQLDescribeParam anyway. We just bind as SQL_C_CHAR with whatever length the data is as the precision.

**Comment by kadler** [comment]
Looks like the docs were fixed in 7.2: https://www.ibm.com/docs/en/i/7.2?topic=functions-sqlbindparameter-bind-parameter-marker-buffer as it now mentions `ValueType`, not `ParameterType`.
